### ISSUE TITLE
Add support for reading out box sensors

### ISSUE THREAD

**Issue by Pinkel** [arnemauer/Ducobox-ESPEasy-Plugin#10]
Currently I have a RH box sensor installed; it would be nice to be able to read this out as well

**Comment by Pinkel** [comment]
Pull request #11 adds the support and works for more.
Most likely it makes sense to first handle pull request #7  and #9

**Comment by nielsvn92** [comment]
Awesome, I'm now able to read out my box sensors!

**Comment by Pinkel** [comment]
@nielsvn92 
If it works for you and me, let's close this issue :)
