### ISSUE TITLE
No fanspeed and countdown

### ISSUE THREAD

**Issue by MPeek1995** [arnemauer/Ducobox-ESPEasy-Plugin#109]
I cant add a sensor to read the countdown second and the sensor with the fanspeed is permantly on zero. 
Could this be a big in the firmware? When i configured a serial gateway myself to only read the values and there it worked. 

I think this is my firmware: ESP_Easy_mega_20220530_custom_ESP8266_4M1M

![image](https://user-images.githubusercontent.com/31782215/172066906-f8ecedda-1460-44a0-be1a-5c57cb551e62.png)

**Comment by arnemauer** [comment]
What do you mean by:
I cant add a sensor to read the countdown second 

And

When i configured a serial gateway myself to only read the values and there it worked.
