### ISSUE TITLE
P151: Firmware 20220530 no fanspeed

### ISSUE THREAD

**Issue by bartlauwers53** [arnemauer/Ducobox-ESPEasy-Plugin#110]
I've just updated my unit (Gateway 7A) to the latest firmware after having issues with the countdown time before. This seems to work fine now. EDIT: this value still hangs, this time on 325(before, it was 295 and 305 very ofte) for unknown reasons from time to time, but on other moments, 4720 is possible as well. I only expect this countdown time to become active when I manually set the unit to a temporary state (Low, Mid or High) which should last for 15 minutes(900 seconds). 
On the other side: I don't see a rpm value for the fanspeed anymore from the plugin DUCO Serial GW - FanSpeed. The value on the devices page remains 0. 
What I've tried: 
- reboot the gateway. 
- removed and then added the plugin for the fanspeed again, also on another line number. 

The DUCO Serial Gateway device with the "Ventilation_Percentage" output seems to work fine. 
Could this be a bug? Seems partially the same as what @mpeek1995 describes?

**Comment by arjan-io** [comment]
Ik kan dit bevestigen (en heb daar reed mail contact over gehad). Ter toevoeging;
- bij mij update de Fanspeed zodra ik in de 'tools' pagina de log bekijk. Het is dan een van de eerste items die voorbij komt
- De interval staat op 60 seconden
- Andere waarden worden naar dezelfde controller gestuurd mbt mqtt en werken wel
- Het niet updaten/vastlopen van de countdown kan ik niet bevestigen maar daarvoor heb ik zelf een vangnet ingebouwd in mijn domotica. Ventmode naar 0 -> update countdown met 0

**Comment by bartlauwers53** [comment]
Ook in de log onder tools staat de fanspeed hier op 0.

**Comment by arnemauer** [comment]
Ik ga er deze week naar kijken :)

**Comment by bartlauwers53** [comment]
Thanks. Ik ben even op vakantie dus zal pas na de 27e kunnen checken.

**Comment by arnemauer** [comment]
Wanneer je in de plugin "Log serial messages to syslog" aanzet. Wat zien jullie dan terug in de weblog?

**Comment by arjan-io** [comment]
Ik heb dit voor de 'gewone' log (dus niet met debug enabled). De fanspeed stond voor ik de log opende al dagen op 362rpm.
```
1547221917: WD   : Uptime 25787 ConnectFailures 0 FreeMem 18256 WiFiStatus 3 ESPeasy internal wifi status: Conn. IP Init
1547229471: [P150] RF GW: UPDATE by PLUGIN_READ
1547236308: [P156] DUCO FanSpeed: start read, eventid:6
1547236308: [P156] DUCO FanSpeed: Start reading fanspeed
1547236489: [P156] DUCO FanSpeed: Received correct response on fanspeed
1547236495: [P156] DUCO FanSpeed: Fanspeed: 2045 RPM
1547236495: [P156] DUCO FanSpeed: End of message received.
1547236495: [P156] DUCO FanSpeed: Stop reading from serial
1547246171: [P151] DUCO SER GW: Start readNetworkList
1547246322: [P151] DUCO SER GW: Received correct response on network
1547246335: [P151] DUCO SER GW: Send command successfull!
1547246362: [P151] DUCO SER GW: Ducobox row found!
1547246363: [P151] DUCO SER GW: New Ventilationmode value: 3
1547246363: [P151] DUCO SER GW: New Countdown value: 800
1547246363: [P151] DUCO SER GW: New Ventilation_Percentage value: 100
1547246364: [P151] DUCO SER GW: New Current_Fan_Value value: 81
1547246422: [P151] DUCO SER GW: End of message received.
1547246422: [P151] DUCO SER GW: Stop reading from serial
1547247370: [P151] DUCO SER GW: New value for Countdown
1547251917: WD   : Uptime 25788 ConnectFailures 0 FreeMem 18312 WiFiStatus 3 ESPeasy internal wifi status: Conn. IP Init
```

Met debug enabled heb ik het volgende:
```
1547401917: WD   : Uptime 25790 ConnectFailures 0 FreeMem 18152 WiFiStatus 3 ESPeasy internal wifi status: Conn. IP Init
1547409471: [P150] RF GW: UPDATE by PLUGIN_READ
1547426171: [P151] DUCO SER GW: Start readNetworkList
1547426322: [P151] DUCO SER GW: Received correct response on network
1547426337: [P151] DUCO SER GW: Send command successfull!
1547426362: [P151] DUCO SER GW: Ducobox row found!
1547426363: [P151] DUCO SER GW: New Ventilationmode value: 3
1547426363: [P151] DUCO SER GW: New Countdown value: 620
1547426363: [P151] DUCO SER GW: New Ventilation_Percentage value: 100
1547426364: [P151] DUCO SER GW: New Current_Fan_Value value: 81
1547426422: [P151] DUCO SER GW: End of message received.
1547426422: [P151] DUCO SER GW: Stop reading from serial
1547427369: [P151] DUCO SER GW: New value for Current_Fan_Value
1547427377: [P151] DUCO SER GW: New value for Countdown
1547431918: WD   : Uptime 25791 ConnectFailures 0 FreeMem 18496 WiFiStatus 3 ESPeasy internal wifi status: Conn. IP Init
1547443756: [P156] DUCO FanSpeed: start read, eventid:6
1547443756: [P156] DUCO FanSpeed: Start reading fanspeed
1547443922: [P156] DUCO FanSpeed: ROW: 1 bytes read:8
1547443923: [P156] DUCO FanSpeed: Pakket ontvangen: 66616E7370656564 END
1547443923: [P156] DUCO FanSpeed: Received correct response on fanspeed
1547443927: [P156] DUCO FanSpeed: ROW: 2 bytes read:51
1547443929: [P156] DUCO FanSpeed: Pakket ontvangen: 202046616E53706565643A2041637475616C2032303438205B72706D5D202D2046696C74657265642032303
1547443979:  END
1547443980: [P156] DUCO FanSpeed: Fanspeed: 2049 RPM
1547443980: [P156] DUCO FanSpeed: ROW: 3 bytes read:6
1547443981: [P156] DUCO FanSpeed: Pakket ontvangen: 2020446F6E65 END
1547443981: [P156] DUCO FanSpeed: ROW: 4 bytes read:2
1547443981: [P156] DUCO FanSpeed: Pakket ontvangen: 2020 END
1547443981: [P156] DUCO FanSpeed: End of message received.
1547443982: [P156] DUCO FanSpeed: Stop reading from serial
1547446011: [P154] DUCO Ext. CO2 Sensor: start read, eventid:5
1547446011: [P154] DUCO Ext. CO2 Sensor: Read external CO2 sensor.
1547446011: [P154] DUCO Ext. CO2 Sensor: Start read external sensor. NodeAddress: 2. Type: CO2
1547446331: [P154] DUCO Ext. CO2 Sensor: Command confirmed by ducobox
1547446344: [P154] DUCO Ext. CO2 Sensor: Send command successfull!
1547446371: [P154] DUCO Ext. CO2 Sensor: CO2 PPM: 417 = 417 PPM
1547446371: [P154] DUCO Ext. CO2 Sensor: End of message received.
1547446371: [P154] DUCO Ext. CO2 Sensor: Stop reading from serial
```

**Comment by bartlauwers53** [comment]
Als ik in tools bij advanced nog de debuglog aanzet zie ik dit(en hierna ga ik op vakantie, en kan ik niet meer bij m’n lokale gateway ;-) )
11465787: 11465778 - 11465787 = 9
11466107: 11466087 - 11466107 = 20
11466407: 11466396 - 11466407 = 11
11468867: 11468866 - 11468867 = 1
11469187: 11469175 - 11469187 = 12
11469487: 11469484 - 11469487 = 3
11471962: 11471953 - 11471962 = 9
11472282: 11472262 - 11472282 = 20
11472525: EVENT: SERGW_VentMode#Ventilationmode=0
11472591: 11472572 - 11472591 = 19
11472677: [P151] DUCO SER GW: ROW: 1 bytes read:7Pakket ontvangen: 6E6574776F726B END
11472678: [P151] DUCO SER GW: ROW: 2 bytes read:10Pakket ontvangen: 20204E6574776F726B3A END
11472691: [P151] DUCO SER GW: Send command successfull!
11475051: 11475040 - 11475051 = 11
11475351: 11475349 - 11475351 = 2
11475671: 11475658 - 11475671 = 13
11478131: 11478128 - 11478131 = 3
11478451: 11478436 - 11478451 = 15
11478751: 11478745 - 11478751 = 6
11481231: 11481215 - 11481231 = 16
11481531: 11481524 - 11481531 = 7
11481851: 11481833 - 11481851 = 18
11484311: 11484303 - 11484311 = 8
11484631: 11484611 - 11484631 = 20
11484931: 11484920 - 11484931 = 11
11487391: 11487390 - 11487391 = 1
11487711: 11487699 - 11487711 = 12
11488011: 11488008 - 11488011 = 3
11490393: EVENT: Clock#Time=Mon,12:34
11490491: 11490478 - 11490491 = 13
11490791: 11490786 - 11490791 = 5
11491111: 11491096 - 11491111 = 15
11491948: WD   : Uptime 192 ConnectFailures 0 FreeMem 18000 WiFiStatus 3 ESPeasy internal wifi status: Conn. IP Init
11493571: 11493565 - 11493571 = 6
11493891: 11493874 - 11493891 = 17
11494191: 11494183 - 11494191 = 8
11496311: 11496306 - 11496311 = 5
11496671: 11496653 - 11496671 = 18
11496971: 11496961 - 11496971 = 10
11497271: 11497270 - 11497271 = 1
11499751: 11499740 - 11499751 = 11
11500051: 11500049 - 11500051 = 2
11500371: 11500358 - 11500371 = 13
11501111: 11501102 - 11501111 = 9
11502831: 11502828 - 11502831 = 3
11503151: 11503137 - 11503151 = 14
11503451: 11503446 - 11503451 = 5
11505931: 11505915 - 11505931 = 16
11506231: 11506224 - 11506231 = 7
11506551: 11506533 - 11506551 = 18
11509011: 11509002 - 11509011 = 9
11509331: 11509311 - 11509331 = 20
11509631: 11509620 - 11509631 = 11
11512100: 11512090 - 11512100 = 10
11512400: 11512398 - 11512400 = 2
11512720: 11512707 - 11512720 = 13
11515180: 11515177 - 11515180 = 3
11515500: 11515486 - 11515500 = 14
11515800: 11515795 - 11515800 = 5
11518280: 11518265 - 11518280 = 15
11518580: 11518573 - 11518580 = 7
11518900: 11518882 - 11518900 = 18
11520645: EVENT: DUCO_VG_RF#Ventmode=0
11520722: EVENT: SERGW_CO2#CO2_PPM=405
11520765: EVENT: SERGW_Box_TempVocht#Temperature=22.4
11520765: EVENT: SERGW_Box_TempVocht#Relative_humidity=48.04
11520836: EVENT: SERGW_countdown#Countdown=0
11520875: EVENT: SERGW_FanPercentage#Ventilation_Percentage=10.00
11520914: EVENT: SERGW_FanSpeed#FanSpeed=395
11520932: [P152] DUCO BOX SENSOR: CO2 PPM: 404 = 404 PPM
11521360: 11521352 - 11521360 = 8
11521616: [P153] DUCO BOX SENSOR: RH: 4800 = 48.00%
11521617: [P153] DUCO BOX SENSOR: TEMP: 224 = 22.4Â°C
11521680: 11521661 - 11521680 = 19
11521948: WD   : Uptime 192 ConnectFailures 0 FreeMem 17712 WiFiStatus 3 ESPeasy internal wifi status: Conn. IP Init
11521980: 11521970 - 11521980 = 10
11522571: [P156] DUCO FanSpeed: Pakket ontvangen: 66616E7370656564 END
11522574: [P156] DUCO FanSpeed: Pakket ontvangen: 202046616E53706565643A2041637475616C20333932205B72706D5D202D2046696C7465726564203339342
11522574: [P156] DUCO FanSpeed: Fanspeed: 394 RPM
11522575: [P156] DUCO FanSpeed: Pakket ontvangen: 2020446F6E65 END
11522575: [P156] DUCO FanSpeed: Pakket ontvangen: 2020 END
11524460: 11524440 - 11524460 = 20
11524760: 11524749 - 11524760 = 11
11525060: 11525058 - 11525060 = 2
11527540: 11527528 - 11527540 = 12
11527840: 11527836 - 11527840 = 4
11528160: 11528145 - 11528160 = 15
11530620: 11530615 - 11530620 = 5
11530940: 11530924 - 11530940 = 16
11531240: 11531233 - 11531240 = 7
11532481: EVENT: SERGW_VentMode#Ventilationmode=0
11532621: [P151] DUCO SER GW: ROW: 1 bytes read:7Pakket ontvangen: 6E6574776F726B END
11532622: [P151] DUCO SER GW: ROW: 2 bytes read:10Pakket ontvangen: 20204E6574776F726B3A END
11532638: [P151] DUCO SER GW: Send command successfull!
11533716: 11533703 - 11533716 = 13
11534016: 11534012 - 11534016 = 4
11534336: 11534321 - 11534336 = 15
11536796: 11536790 - 11536796 = 6
11537116: 11537099 - 11537116 = 17
11537416: 11537408 - 11537416 = 8
11539896: 11539878 - 11539896 = 18
11540196: 11540187 - 11540196 = 9
11540496: 11540496 - 11540496 = 0
11541116: 11541114 - 11541116 = 2
11545916: 11545915 - 11545916 = 1
11546237: 11546224 - 11546236 = 12
11546536: 11546533 - 11546536 = 3
11549016: 11549003 - 11549016 = 13
11549316: 11549312 - 11549316 = 4
11549636: 11549621 - 11549636 = 15
11550393: EVENT: Clock#Time=Mon,12:35
11551948: WD   : Uptime 193 ConnectFailures 0 FreeMem 17904 WiFiStatus 3 ESPeasy internal wifi status: Conn. IP Init
11552096: 11552090 - 11552096 = 6
11552416: 11552399 - 11552416 = 17
11552716: 11552707 - 11552716 = 9
11555196: 11555178 - 11555196 = 18
11555496: 11555486 - 11555496 = 10
11555796: 11555795 - 11555796 = 1
11558276: 11558265 - 11558276 = 11
11558576: 11558574 - 11558576 = 2
11558896: 11558883 - 11558896 = 13
11561356: 11561353 - 11561356 = 3
11561676: 11561661 - 11561676 = 15
11561976: 11561970 - 11561976 = 6

**Comment by arnemauer** [comment]
Jullie hebben het dus allebei over een andere plugin, klopt dat?

@bartlauwers53 Jij hebt het over fanspeed uit plugin 151 DUCO Serial Gateway
@arjan-io  Jij hebt het over [P156] DUCO FanSpeed

**Comment by arnemauer** [comment]
[ESP_Easy_mega_20220630_custom_ESP8266_4M1M.zip](https://github.com/arnemauer/Ducobox-ESPEasy-Plugin/files/9022327/ESP_Easy_mega_20220630_custom_ESP8266_4M1M.zip)

Willen jullie deze bin eens proberen? Is het probleem daarmee opgelost?

**Comment by bartlauwers53** [comment]
> [ESP_Easy_mega_20220630_custom_ESP8266_4M1M.zip](https://github.com/arnemauer/Ducobox-ESPEasy-Plugin/files/9022327/ESP_Easy_mega_20220630_custom_ESP8266_4M1M.zip)
> 
> Willen jullie deze bin eens proberen? Is het probleem daarmee opgelost?

Sorry voor de late reactie(vakantie) maar nog even een update: ik zag dus op vakantie in mijn home assistant(die ik wel op afstand kan benaderen) dat er ineens wel waarden verschenen bij de fanspeed van Plug-in 151. Eerder was dat dus niet zo, niet bij de devices pagina en ook niet in de logs. Inmiddels geconstateerd dat de waarde nu al drie dagen ongeveer op 353 rpm staat. Een reboot van de gateway lost dat niet op. 

Wil de nieuwe build best testen maar moet even kijken wanneer ik daar aan toe kom.

**Comment by arjan-io** [comment]
Ik heb de firmware er op gezet. Bij mij nog steeds het zelfde met de Fanspeed (rpm, P156). Log openen, dan komt de update van de Fanspeed pas door.

In de log had ik dit:
```
284138: WD   : Uptime 5 ConnectFailures 0 FreeMem 15496 WiFiStatus 3 ESPeasy internal wifi status: Conn. IP Init
290054: 290052 - 290054 = 2
308008: 307997 - 308008 = 11
308328: 308313 - 308328 = 15
308330: [P150] RF GW: 0 - Ignore message, not our networkID.
308348: 308340 - 308348 = 8
308349: [P150] RF GW: 0 - Ignore message, not our networkID.
308409: [P150] RF GW: RX FIFO OVERFLOW -> idle, flush RX FIFO and switch to RX state.
308668: 308654 - 308668 = 14
308669: [P150] RF GW: 0 - Ignore message, not our networkID.
308988: 308971 - 308988 = 17
308989: [P150] RF GW: 0 - Ignore message, not our networkID.
309348: 309337 - 309348 = 11
309350: [P150] RF GW: 0 - Ignore message, not our networkID.
312884: [P150] RF GW: UPDATE by PLUGIN_READ
313144: [P151] DUCO SER GW: New Current_Fan_Value value: 36
313203: [P151] DUCO SER GW: End of message received.
313203: [P151] DUCO SER GW: Stop reading from serial
313590: [P151] DUCO SER GW: New value for Current_Fan_Value
313597: [P151] DUCO SER GW: New value for Countdown
313597: [P154] DUCO Ext. CO2 Sensor: start read, eventid:5
313597: [P154] DUCO Ext. CO2 Sensor: Read external CO2 sensor.
313597: [P154] DUCO Ext. CO2 Sensor: Start read external sensor. NodeAddress: 2. Type: CO2
313926: [P154] DUCO Ext. CO2 Sensor: Command confirmed by ducobox
313937: 313930 - 313937 = 7
313938: [P150] RF GW: 0 - Ignore message, not our networkID.
313939: [P154] DUCO Ext. CO2 Sensor: Send command successfull!
313966: [P154] DUCO Ext. CO2 Sensor: CO2 PPM: 440 = 440 PPM
313976: [P154] DUCO Ext. CO2 Sensor: End of message received.
313976: [P154] DUCO Ext. CO2 Sensor: Stop reading from serial
314012: 313959 - 314012 = 53
314139: WD   : Uptime 5 ConnectFailures 0 FreeMem 15624 WiFiStatus 3 ESPeasy internal wifi status: Conn. IP Init
314582: [P156] DUCO FanSpeed: start read, eventid:6
314583: [P156] DUCO FanSpeed: Start reading fanspeed
314763: [P156] DUCO FanSpeed: ROW: 1 bytes read:8
314764: [P156] DUCO FanSpeed: Pakket ontvangen: 66616E7370656564 END
314764: [P156] DUCO FanSpeed: Received correct response on fanspeed
314768: [P156] DUCO FanSpeed: ROW: 2 bytes read:51
314770: [P156] DUCO FanSpeed: Pakket ontvangen: 202046616E53706565643A2041637475616C2031303136205B72706D5D202D2046696C74657265642031303
314820:  END
314821: [P156] DUCO FanSpeed: Fanspeed: 1013 RPM
314829: [P156] DUCO FanSpeed: ROW: 3 bytes read:6
314830: [P156] DUCO FanSpeed: Pakket ontvangen: 2020446F6E65 END
314830: [P156] DUCO FanSpeed: ROW: 4 bytes read:2
314830: [P156] DUCO FanSpeed: Pakket ontvangen: 2020 END
314830: [P156] DUCO FanSpeed: End of message received.
314830: [P156] DUCO FanSpeed: Stop reading from serial
```
De Device-pagina update ook heel laat. De berichten via MQTT worden een stuk eerder verstuurd dan dat de waardes op de device-pagina worden weer gegeven. Uiteindelijk is bij mij MQTT het belangrijkst...

**Comment by arnemauer** [comment]
@bartlauwers53 In jou log zie ik überhaupt geen regels met betrekking tot de fanspeed. SERGW_FanSpeed#FanSpeed=0 is van P151?

**Comment by arnemauer** [comment]
Ik denk dat dit het probleem is: 
https://github.com/arnemauer/Ducobox-ESPEasy-Plugin/blob/eb60c685c2589d9cce4892944aba9730230f4701/_P156_DucoSerialFanSpeed.ino#L108

serialPortInUseByTask = event->TaskIndex; is per ongeluk onder de if statement komen te staan waardoor plugin de seriele poort alleen kan "claimen" als je debug aan hebt.

**Comment by arnemauer** [comment]
Het is gefixt in de nieuwe binary: https://github.com/arnemauer/Ducobox-ESPEasy-Plugin/blob/master/Binaries/Binary%20based%20on%20ESPEasy_mega-20220427/20220704%20Firmware%20417d280%2004-07-2022%20(ESPEasy%20mega-20220427).bin

**Comment by MPeek1995** [comment]
Dit lijkt te werken! Veel dank!

Rpm zie ik in log en in devices.

Op do 30 jun. 2022 om 20:43 schreef bartlauwers53 ***@***.***
