### ISSUE TITLE
When ESP8266 reboots, the Duco goes to High Fan RPM

### ISSUE THREAD

**Issue by Jozziej** [arnemauer/Ducobox-ESPEasy-Plugin#121]
Is there a way to make sure that when the ESP8266 reboots, the Duco does not go to High?
Simply I always have the Duco at Permanent Low, which is changed to 20% in the Duco box itself.

**Comment by arnemauer** [comment]
After reboot it is assumed that the fan is running in automatic mode. 
https://github.com/arnemauer/Ducobox-ESPEasy-Plugin/blob/master/_P150_DucoRFGateway.ino#L21

The gateway will send a subscribe message to the Ducobox to get the current ventilation mode.

**Comment by Jozziej** [comment]
For some reason the ventilation does go to High every time the esp8266 lost connection or did a reboot. Is there a way to force a certain ventilation value, like permanent low?

**Comment by arnemauer** [comment]
Do you use mqtt? Could you try to disable that controller and reboot? Is de ducobox still changing ventilation mode to high after a reboot?

**Comment by Jozziej** [comment]
Yes I use MQTT to Home Assistant, when I disable the MQTT controller and reboot the ESP, the Duco box does not change the Fan to High. As soon as I enable the Mqtt controller again, instand change to Fan High.

**Comment by arnemauer** [comment]
It is not the plugin changing the ventilationmode. If you open the mqtt controller configuration page, do you have the retain checkbox on?

**Comment by Jozziej** [comment]
Yes

![image](https://user-images.githubusercontent.com/63554049/202404170-0f80df3b-cf66-4899-9f3b-4b1d3c972af6.png)

**Comment by arnemauer** [comment]
Uncheck it...

**Comment by Jozziej** [comment]
Tried that, and makes no difference

**Comment by Jozziej** [comment]
Hi Arne you can close this issue.
For some reason the Mqtt broker retained the Ventilation High cmd. Solved that.
