### ISSUE TITLE
Formulier ingevuld, maar nog geen reactie

### ISSUE THREAD

**Issue by Theetjuh** [arnemauer/Ducobox-ESPEasy-Plugin#124]
Hey Arne,

Ik heb in oktober het formulier ingevuld, maar heb helaas nog geen reactie gehad.
Nu heb ik niet echt haast, maar wil er meer zeker van zijn dat alles goed is aangekomen.

Groeten,
Mathé

**Comment by arnemauer** [comment]
Hej,

Ik heb vandaag de pcbs binnen gekregen. Op www.ventilationgateway.com vind je de huidige status. Wanneer ze gateways in elkaar zitten en getest zijn stuur ik een email naar iedereen die het formulier heeft ingevuld.

**Comment by Theetjuh** [comment]
Ok top, geen probleem … die website nog niet eerder gezien. Als je bij het formulier kijkt staat daar nog half oktober trouwens :)
