### ISSUE TITLE
Plugin sometimes pushes incorrect values to domoticz

### ISSUE THREAD

**Issue by Pinkel** [arnemauer/Ducobox-ESPEasy-Plugin#13]
It can be seen when looking at the domoticz logs, that sometimes an incorrect (zero) value is transmitted.

I think this happens because the value '0' is also used when it is not available, instead of 'NaN'.

Pull request incoming... Note; I still need to have it at least a day running to make sure if this fixes the problem

**Comment by Pinkel** [comment]
![co2_ppm](https://user-images.githubusercontent.com/5629148/56718459-14bc5c00-673f-11e9-8cbb-a8cc3dc40da4.JPG)

**Comment by arnemauer** [comment]
Fixed :) Thank you!
