### ISSUE TITLE
RF gateway blijft disabled

### ISSUE THREAD

**Issue by bartsnijder** [arnemauer/Ducobox-ESPEasy-Plugin#142]
Ik probeer de CC1101 RF gateway toe te voegen, maar na submitten blijft de plugin op disabled staan.

**Comment by arnemauer** [comment]
Je geeft te weinig informatie om je verder te helpen.

- Heb je alle stappen van de wiki doorlopen?
- Wat is het probleem?
- Wat heb je zelf al geprobeerd?
- Wat voor hardware gebruik je?
- Welke versie firmware gebruik je?

**Comment by bartsnijder** [comment]
Ik heb de wiki doorlopen.
Ik gebruik een D1 mini pro met eem RF Transceiver 868MHz CC1101 (Build: [ESP_Easy_mega_20230518_custom_ESP8266_4M1M May 18 2023])
De seriele gateway is operationeel maar de DUCO ventilation remote kan niet enabled worden. Ik volg de exacte stappen van de site, maar na het selecteren van "enable" en submit, blijft de unit disabled.

update: de logfile geeft deze foutmelding
[P150] RF GW: Initialisation -> calibration failed. No response from CC1101 or status not idle.

**Comment by arnemauer** [comment]
De foutmelding geeft aan dat de esp niet kan communiceren met je CC1101. 
Heb je de draden gecontroleerd?

**Comment by bartsnijder** [comment]
Niet meer gereageerd, excuses. De CC1101 module bleek defect, na 1 op 1 vervanging werkt alles zoals verwacht. Bedankt voor het meedenken
