### ISSUE TITLE
ordering on https://ventilationgateway.com/ is broken

### ISSUE THREAD

**Issue by frko** [arnemauer/Ducobox-ESPEasy-Plugin#147]
Hi, I am trying to order a ducobox serial-2-usbc cable on the website but the payment provider integration seems broken (errors in the console and ideal doesnt how an option to select a bank)

<img width="1021" alt="image" src="https://github.com/arnemauer/Ducobox-ESPEasy-Plugin/assets/1576993/fc13c6aa-a131-4175-a7e0-47303ea031b6">

Is this supposed to be still working & available?

Would love to hear from you, regards, Frank

**Comment by arnemauer** [comment]
Its fixed :)
