### ISSUE TITLE
D1 crashes after enabling Duco device

### ISSUE THREAD

**Issue by robbertcoppens** [arnemauer/Ducobox-ESPEasy-Plugin#18]
Hi, right after enabling the Duco device in ESP Easy web interface, the D1 crashes and only re-flashing can restore it. I'm using your compiled firmware.bin. Any clue?

**Comment by arnemauer** [comment]
Hi, could you post a photo of your setup? Did you select the correct  pin on the device config page?

**Comment by arnemauer** [comment]
Espeasy fixes a big wifi bug in Release mega-20190903. If you flash the newest firmware the D1 wouldnt crash that often anymore :)

**Comment by robbertcoppens** [comment]
Thanks! I will try if that works. Will post some pics if still issues.

**Comment by robbertcoppens** [comment]
Updating the firmware helped. Next there was an issue with the RF module, ordered a new one and now it's working fine. Thanks!
