### ISSUE TITLE
Duco laten werken met domoticz 

### ISSUE THREAD

**Issue by broekieman** [arnemauer/Ducobox-ESPEasy-Plugin#19]
Hoi,

Heb je een oplossing om de duco box draadloos te laten werken met domoticz. Ik wil via een blocky event de ventilatie op hoogste stand laten draaien zodra de luchtvochtigheid in de badkamer omhoog gaat. Ik heb een bedrade de Co2 schakelaar in de woonkamer en een draadloze op de badkamer. Domoticz gebruik ik al en sensors ook.

**Comment by arnemauer** [comment]
Beste Broekieman,

De Ducobox RF/serial module werkt out-of-the box met domoticz! :) Je verbindt de module via wifi met je thuisnetwerk. Vervolgens kun je domoticz zo instellen dat je de ventilatiewaarden ziet en ook de ventilatiestanden van de Ducobox kan aansturen. Op de wiki vind je hier informatie over hoe de gateway werkt met Domoticz: https://github.com/arnemauer/Ducobox-ESPEasy-Plugin/wiki/Configuration-of-Domoticz

Je moet nog wel de gateway bouwen: https://github.com/arnemauer/Ducobox-ESPEasy-Plugin/wiki/Hardware---RF-gateway 

Of je kan hem kant en klaar bestellen: https://forms.gle/PX1tb2zWaGPE9N7P9
![alt text](https://lh3.googleusercontent.com/BwMq_kRBSWiwzLijpkmwPA1R2sJZLi7zy4GyY_how3kKHnGUe9z8nwNkQxhgmt_3JARkmPTbv7FDmz99WHIDQ6mGINUzBPpCQxCJR7BuxoFqu5GyYdGNuIPVW96-RQD9ebi2uOOi0qQMArJFxurA-l80G9yedwmcSlkiwf3SRvTiT6x6ZZG6vA01nDOni1H-FuWfYvo7SWxxftWyZ-NyQvb3njz-nzTb0cMnRHbCEaqT4UBUpOQsn-rpI0YrKb8rvKOaej1RvaKkod9okyXCCn8X40NpM0o04w3SbqwSpESJ7hqvjz--geNArxl7PCEA0UW3I3IfthfQQJU_csnE970Vhe4jU0bwnGglWz2aplGbeDiMzHTiZzZPQh7z5NSvGXKWVCCnN63BEo6vuuTTtMcAY0CYZ1ES1yyu0iymhjRiZbabDb6GXdfPrybYpEv4iB5yM7qDF8k6ruhUFaU8mYdV-I1Z_eVRadBLM7QW-XyTBrdH7gM0OG1KhW3qdEt1Ysr6_0GKrQ7MHowRg-kUCMh-8XDiBYesPoEjRMJKZ0ps6zgtTaIdvBWv-5qbaxoA8tkoS_zBqwKdmUqTlLbR1Gdcrcgdejus7f3S6mF4PyTGx_hg2v_EsrepZOmgZljLt41QRuViZft-SJQR0X0TU57VdC7-c2VgbV325QjTjPjNF2VC0NkvolwzNDdHPYAtpYrBypOkmGv5lghzeqkYk-uGWJHcq-78vN3ARnh8IvCegAtiDA=w300)

**Comment by broekieman** [comment]
Zijn er 2 soorten hardware of zitten zowel seriële en rf in het kastje? Kan ik alles uitlezen via een webinterface? Is het dan hetzelfde wat je ermee kunt als de techneuten/monteurs van Duco. Geef alvast je gegevens voor het bestellen want ik vind het leuk om ermee aan de slag te gaan. Met vriendelijke groet Maarten Met vriendelijke groet,Maarten Broekman-------- Oorspronkelijk bericht --------Onderwerp: Re: [arnemauer/Ducobox-ESPEasy-Plugin] Duco laten werken met domoticz  (#19)Van: arnemauer Aan: arnemauer/Ducobox-ESPEasy-Plugin Cc: broekieman ,Author Beste Broekieman,
De Ducobox RF/serial module werkt out-of-the box met domoticz! :) Je verbindt de module via wifi met je thuisnetwerk. Vervolgens kun je domoticz zo instellen dat je de ventilatiewaarden ziet en ook de ventilatiestanden van de Ducobox kan aansturen. Op de wiki vind je hier informatie over hoe de gateway werkt met Domoticz: https://github.com/arnemauer/Ducobox-ESPEasy-Plugin/wiki/Configuration-of-Domoticz
Je moet nog wel de gateway bouwen: https://github.com/arnemauer/Ducobox-ESPEasy-Plugin/wiki/Hardware---RF-gateway
Of je kan hem kant en klaar bestellen: https://forms.gle/PX1tb2zWaGPE9N7P9

**Comment by broekieman** [comment]
> Beste Broekieman,
> 
> De Ducobox RF/serial module werkt out-of-the box met domoticz! :) Je verbindt de module via wifi met je thuisnetwerk. Vervolgens kun je domoticz zo instellen dat je de ventilatiewaarden ziet en ook de ventilatiestanden van de Ducobox kan aansturen. Op de wiki vind je hier informatie over hoe de gateway werkt met Domoticz: https://github.com/arnemauer/Ducobox-ESPEasy-Plugin/wiki/Configuration-of-Domoticz
> 
> Je moet nog wel de gateway bouwen: https://github.com/arnemauer/Ducobox-ESPEasy-Plugin/wiki/Hardware---RF-gateway
> 
> Of je kan hem kant en klaar bestellen: https://forms.gle/PX1tb2zWaGPE9N7P9
> ![alt text](https://camo.githubusercontent.com/405ab9d292b2139e1dc471b6cf1999d6b183d318/68747470733a2f2f6c68332e676f6f676c6575736572636f6e74656e742e636f6d2f42774d715f6b5242535769777a4c696a706b6d775041315232734a5a4c69377a79344779595f686f77336b4b486e475565397a386e774e6b517868676d745f334a41526b6d505462763746446d7a39395748494451366d47494e557a425070435178434a52374275786f4671753547795964474e754950565739362d5251443965626932754f4f693071514d41724a46787572412d6c38304739796564776d63536c6b697766335352765469543678365a5a4736764130316e444f6e6931482d4675576659766f3753577878667457795a2d4e79517662336e6a7a2d6e7a546230634d6e524862434561715434554255704f51736e2d7270493059724b623872764b4f61656a315276614b6b6f64396f6b795843436e385834304e704d306f3034773353627177537045534a376871766a7a2d2d67654e4172786c3750434541305557334933496674686651514a555f63736e45393730566865346a553062776e47676c577a3261706c47626544694d7a4854695a7a5a505168377a354e537647584b575643436e4e363342456f367675755454744d6341593043595a314553317979753069796d686a52695a62616244623647586466507279625970457634694235794d37714446386b3672756855466155386d5964562d49315a5f6556526164424c4d3751572d5879544272644837674d304f47314b6857337164457431597372365f30474b7251374d486f7752672d6b55434d682d3858446942596573506f456a524d4a4b5a307073367a677454614964764257762d35716261786f4138746b6f535f7a4271774b646d5571546c4c62523147646372636764656a757337663353366d463450795447785f686732765f45737265705a4f6d675a6c6a4c74343151527556695a66742d534a515230583054553537566443372d633256676256333235516a546a506a4e46325643304e6b766f6c777a4e446448505941747059724279704f6b6d4776356c67687a65716b596b2d7547574a4863712d3738764e3341526e6838497643656741746944413d77333030)

Hoi Arne,

Ik weet niet hoe het precies hier werkt met berichten. Kun je nog even naar mijn vragen kijken?

**Comment by arnemauer** [comment]
**- Zijn er 2 soorten hardware of zitten zowel seriële en rf in het kastje?** 
Beide zitten in de gateway. De seriële gateway werkt via een kabel die je aansluit op de ducobox. Je kan daarmee de ventilatiestand, ventilatiepercentage, co2 PPM en co2 temperatuur. Via de seriele kabel kan je echter niet ducobox aansturen (ventilatiestand veranderen). Daarom is er een RF-gateway die zich gedraagt als draadloze afstandbediening. 

**- Kan ik alles uitlezen via een webinterface?** 
De hierboven genoemde waardes kun je uitlezen.

**Is het dan hetzelfde wat je ermee kunt als de techneuten/monteurs van Duco.** 
Nee, daarvoor kun je beter een losse usb naar serieel kabel gebruiken. Als die kabel een Silicon Labs CP210x chipset heeft werkt hij out of the box met de duco network tool. Dat is de software die installateurs gebruiken om de ducobox verder in te stellen. Het heeft weinig nut om die instellingen via de gateway beschikbaar te stellen omdat je ze daarna toch nooit meer aanpast.

**Comment by broekieman** [comment]
Kan ik dan de waardes via een ipadres uitlezen? Heb je nog een gateway liggen voor me? Graag je gegevens voor betalen. Met vriendelijke groet,Maarten Broekman-------- Oorspronkelijk bericht --------Onderwerp: Re: [arnemauer/Ducobox-ESPEasy-Plugin] Duco laten werken met domoticz  (#19)Van: arnemauer Aan: arnemauer/Ducobox-ESPEasy-Plugin Cc: broekieman ,Author - Zijn er 2 soorten hardware of zitten zowel seriële en rf in het kastje?

Beide zitten in de gateway. De seriële gateway werkt via een kabel die je aansluit op de ducobox. Je kan daarmee de ventilatiestand, ventilatiepercentage, co2 PPM en co2 temperatuur. Via de seriele kabel kan je echter niet ducobox aansturen (ventilatiestand veranderen). Daarom is er een RF-gateway die zich gedraagt als draadloze afstandbediening.

- Kan ik alles uitlezen via een webinterface?

De hierboven genoemde waardes kun je uitlezen.

Is het dan hetzelfde wat je ermee kunt als de techneuten/monteurs van Duco. 

Nee, daarvoor kun je beter een losse usb naar serieel kabel gebruiken. Als die kabel een Silicon Labs CP210x chipset heeft werkt hij out of the box met de duco network tool. Dat is de software die installateurs gebruiken om de ducobox verder in te stellen. Het heeft weinig nut om die instellingen via de gateway beschikbaar te stellen omdat je ze daarna toch nooit meer aanpast.

**Comment by broekieman** [comment]
Ik probeer het nog maar een keer. Je schreef me dat ik een gateway bij je kan kopen. Ik wil dit graag maar ondanks meerdere pogingen om dit te regelen, krijg ik geen enkele reactie. Ja, ik weet dat je geen helpdesk bent maar ik mag op zijn minst toch wel een reactie verwachten als ik je aanbod geaccepteerd heb.

**Comment by arnemauer** [comment]
> Kan ik dan de waardes via een ipadres uitlezen? Heb je nog een gateway liggen voor me? Graag je gegevens voor betalen. Met vriendelijke groet,Maarten Broekman

Ja, zie https://github.com/arnemauer/Ducobox-ESPEasy-Plugin/wiki/Data-uit-Ducobox

> Ik probeer het nog maar een keer. Je schreef me dat ik een gateway bij je kan kopen. Ik wil dit graag maar ondanks meerdere pogingen om dit te regelen, krijg ik geen enkele reactie. Ja, ik weet dat je geen helpdesk bent maar ik mag op zijn minst toch wel een reactie verwachten als ik je aanbod geaccepteerd heb.

Ik vind het jammer dat ik niet aan je verwachting voldaan heb. We hebben het hier echter wel over een paar dagen. In Nederland zijn we helaas verwend met de bol.com 'voor 23.59 uur besteld morgen in huis' verzending. In andere landen zie je dat nauwelijks terug. Dit project is een hobbyproject en mijn gezin gaat voor op alles. Daarom duurt het soms een paar dagen voordat je een reactie van mij krijgt.

Maargoed, mocht snelle installatie en stabiliteit noodzakelijk zijn kan ik je de communication print van Ducobox zelf aanraden: https://www.duco.eu/nl-nl-duco-ventilation-app. Zij kunnen deze voor je installeren en kunnen je ook de verwachte support bieden.

Mocht je alsnog geïnteresseerd zijn in een gateway raad ik je aan om alle pagina's van de de wiki eens door te lezen: https://github.com/arnemauer/Ducobox-ESPEasy-Plugin/wiki
