### ISSUE TITLE
Connect ThingSpeak

### ISSUE THREAD

**Issue by hetSein** [arnemauer/Ducobox-ESPEasy-Plugin#27]
Hi,

Im trying to send the data to ThingSpeak using the following:
Controller IP: 184.106.153.149
Controller port: 80

Credentials: tried the given Channelname and tried the Channel ID
 API key; used the API write key

But,I don't receive data. Can anyone help me out? What I'm doing wrong?

**Comment by arnemauer** [comment]
Ik heb zelf geen ervaring met ThingSpeak. 
Zie je ook iets terug in de weblog? (Tools -> Log) 
Om meer informatie terug te zien in de logs kun je "Web Log Level" op DEBUG zetten (Tools -> Advanced Settings)
