### ISSUE TITLE
Interne timer Duco box

### ISSUE THREAD

**Issue by phoenix-blue** [arnemauer/Ducobox-ESPEasy-Plugin#29]
Hallo,
Is het mogelijk de interne timer (countdown) uit te schakelen in de Duco box.
Ik zou graag de 3 verschillende toerentallen (of eventueel % rpm) vast willen aansturen zonder dat hij na een x tijd weer terug naar low gaat.

**Comment by IgorYbema** [comment]
Duplicate of #28

**Comment by phoenix-blue** [comment]
Thanks, had niet door dat het specifiek om deze functie ging 👍
