### ISSUE TITLE
Wiring scheme Serial Gateway

### ISSUE THREAD

**Issue by nielsvn92** [arnemauer/Ducobox-ESPEasy-Plugin#3]
Hi @arnemauer,

I can't seem to find the wiring scheme for the Serial Gateway. I did find a wiring scheme, but that seems to be long to the RF Gateway. Is that right?

Can you tell me which pins of the WEMOS to connect to which wire?

Kind regards,
Niels

**Comment by arnemauer** [comment]
Hi Niels,

I added a wiki page with information about the serial connection with the ducobox.
https://github.com/arnemauer/Ducobox-ESPEasy-Plugin/wiki/Hardeware----Serial-GW
