### ISSUE TITLE
Na join4 bericht wordt er geen sendJoinFinish verstuurd

### ISSUE THREAD

**Issue by arnemauer** [arnemauer/Ducobox-ESPEasy-Plugin#31]
Alle apparaten die aangesloten zijn op de ducobox krijgen een nodenumber. Binnen het RF netwerk krijgt ieder apparaat een eigen "network address". Vaak is dit hetzelfde als het nodenumber maar het is mogelijk dat dit afwijkt. 

![nodenumber-networkaddress-difference](https://user-images.githubusercontent.com/268051/83728097-5740af80-a646-11ea-918a-2b07087f33b4.png)

In de huidige code wordt gekeken of het nodenumber en het network address gelijk zijn. Als die gelijk zijn wordt de koppeling afgerond. Als die niet gelijk zijn (en dat kan) wordt de koppeling niet afgerond. Zie regel 3:

```
if(validJoin4Packet){
	setLogMessage(F("sendJoinFinish: valid join4 packet received!"));
	if(inDucoPacket.data[5] == inDucoPacket.data[6]){
		this->deviceAddress = inDucoPacket.data[5]; // = new address	
		char logBuf[100];
		snprintf(logBuf, sizeof(logBuf), "sendJoinFinish: new device address is: %u;",this->deviceAddress);
		setLogMessage(logBuf);

		// send ack! from new deviceaddress to address of sender.
		sendAck();
		setLogMessage(F("sendJoinFinish: ACK sent!"));
		ducoDeviceState = ducoDeviceState_joinSuccessful;
	}
}else{
	setLogMessage(F("sendJoinFinish: INVALID join4 packet received!"));
}
```
Een "join4" bericht ziet er als volgt uit: 00 00 7C 3E **XX** **YY**
**XX** = network address
**YY** = node number

@samvdb

**Comment by samvdb** [comment]
firmware 6.4.0 op een duco focus ter info!
