### ISSUE TITLE
Device Address wordt niet opgeslagen na een succesvolle join.

### ISSUE THREAD

**Issue by arnemauer** [arnemauer/Ducobox-ESPEasy-Plugin#34]
Device Address wordt niet opgeslagen na een succesvolle join. Het network id wordt wel opgeslagen.

https://github.com/arnemauer/Ducobox-ESPEasy-Plugin/blob/835d370a4cb78460551996dc833e3b2797d0d9ac/_P150_DucoRFGateway.ino#L248

**Comment by shuffleznl** [comment]
Hoe kan ik het makkelijkst de gateway updaten met deze fix?
