### ISSUE TITLE
Aansturen via serieel

### ISSUE THREAD

**Issue by martenjacobs** [arnemauer/Ducobox-ESPEasy-Plugin#49]
Ik ben er vandaag achter gekomen dat het instellen van de fan via de seriële poort mogelijk is, iets dat voor zover ik weet nog niet algemeen bekend was tot nu toe (maar ik kan het fout hebben):
```
nodesetoverrule 1 100
nodesetoverrule 1 0
```
Zet de fan respectievelijk voluit en op de laagste stand. Wellicht is dat interessant om toe te voegen aan de seriële variant van deze library.

**Comment by arnemauer** [comment]
Je zou nodesetoverrule kunnen gebruiken om de ventilatiestand in % handmatig aan te sturen. Dit heeft wel een aantal nadelen:

1. De stand is niet terug te zien op de bedieningsschakelaars.

2. Je overruled hiermee al je sensoren. Je CO2/luchtvochtigheidssensor zal zelf de ventilatiestand niet kunnen wijzigen ook al is de co2/luchtvochtigheid boven de triggerwaarde.

Zie onderstaande screenshots met "nodesetoverrule 1 100":
![overrule1](https://user-images.githubusercontent.com/268051/90628875-aa2a0c00-e21e-11ea-8775-67a3ff224611.png)
![20200819_130043](https://user-images.githubusercontent.com/268051/90628878-aac2a280-e21e-11ea-8d96-b244502365ad.jpg)
![overrule2](https://user-images.githubusercontent.com/268051/90628881-ab5b3900-e21e-11ea-9bf3-95c33a95bd03.png)

**Comment by martenjacobs** [comment]
Dat vermoedde ik al, en dat is natuurlijk een nadeel als je schakelaars of sensoren hebt, maar dat is bij mij niet het geval 😬

**Comment by martenjacobs** [comment]
Op Tweakers gaf je trouwens aan dat je dacht deze functie flash wear kon veroorzaken. Enig idee hoeveel writes we van dat flash kunnen verwachten?
