### ISSUE TITLE
Duco Energy Premium System

### ISSUE THREAD

**Issue by 26miller** [arnemauer/Ducobox-ESPEasy-Plugin#50]
Ik zie dat de Duco box Silent en Focus ondersteund worden zou het ook werken op deze box Duco Energy Premium System

**Comment by arnemauer** [comment]
Ík denk dat dat wel moet lukken. Heb je dezelfde aansluiting op de printplaat?

![DUCOBOX-CONNECTOR](https://user-images.githubusercontent.com/268051/95511088-41a61280-09b7-11eb-9cb7-0d01af076b99.jpg)

**Comment by 26miller** [comment]
Bord layout is wat anders bij mij maar connector zit er wel volgens mij zal van het weekend eens meten of het klopt.
![board](https://user-images.githubusercontent.com/72555739/95581097-b2d9da00-0a38-11eb-9688-446193c75ccb.jpg)

**Comment by arnemauer** [comment]
Ik ben benieuwd! De gateway is naar je onderweg.
Als het werkt voeg ik hem toe aan de lijst.

**Comment by 26miller** [comment]
Serial connection lijkt te werken ben alleen nog wat aan het stoeien met de data. Lijkt of niet alle data klopt met wat ik zie. Zal in de loop van de week nog wat verder puzzelen. Heb overigens ook een probleem met het ip van van domoticz in te voeren als controller deze valt steeds terug naar een default adres wat ik niet in geef., 
![image](https://user-images.githubusercontent.com/72555739/95682503-d3936280-0be5-11eb-9dbd-cc81403a681a.png)

**Comment by arnemauer** [comment]
Zie de waarschuwing in het rode kader. Het flashgeheugen kan je maar een
maximaal aantal keer beschrijven voordat de chip kapot gaat. Daarom zit er
een bescherming op om te voorkomen dat je dit te vaak doet. Daarvoor dient
de waarschuwing in het rode vak. Opnieuw starten van de gateway reset de
teller.

Op zo 11 okt. 2020 17:19 schreef 26miller <notifications@github.com>:

**Comment by 26miller** [comment]
Had al wel gelezen dat ik power van gateway moest halen maar heb dit waarschijnlijk te kort gedaan. Data komt binnen in domoticz nu. Vooralsnog alleen Ventilationmode en VentilationPercentage overige sensoren op box nog niet aan de praat gekregen.  Word vervolgd..

**Comment by 26miller** [comment]
RF gateway werkt geheel zoals beschreven, Met de serial gateway kan ik de ventilationmode percentage en de gekoppelde afstandbediening uitlezen (CO2 en Temp) de sensoren van de box zelf heb ik (nog) niet aan de praat gekregen, 
Serial gateway verliest af en toe connectie met box maar door gebrek aan tijd dit nog niet verder kunnen onderzoeken.
