### ISSUE TITLE
Serial Gateway waardes uitlezen via home assistant

### ISSUE THREAD

**Issue by sanderlv** [arnemauer/Ducobox-ESPEasy-Plugin#55]
Hallo, onderstaand 2 screenshots van mijn setup:
![image](https://user-images.githubusercontent.com/16528916/97451924-81b44180-1934-11eb-921f-ed16efe1be4c.png)

Via MQTT kan ik (via Node-red diverse waarden sturen en dit werkt top! (RF gateway):
![image](https://user-images.githubusercontent.com/16528916/97452066-a5778780-1934-11eb-8530-45e28a71badd.png)

Maar nu wil ik graag de "output" (Serial gateway) waardes in home assistant krijgen... hoe kan ik deze vanuit de ESPeasy laten versturen? Via MQTT?

De ESP easy is nog niet aangesloten op de duco (kabel/stekkertje besteld) en dus staan de waarden op 0.0 (zie screenshot).. worden deze waarden als ze gevuld worden naar MQTT gestuurd?

Hieronder een screenshot van de MQTT explorer met topic ventilation_gateway
![image](https://user-images.githubusercontent.com/16528916/97452010-97296b80-1934-11eb-8f80-a9bc72a72db2.png)

Oh en zo zie het er in home asssitant uit nu (en daar wil ik de sensoren met waarden graag bijhebben die via de serial gateway moeten komen).

![image](https://user-images.githubusercontent.com/16528916/97452620-377f9000-1935-11eb-91f9-6e72baba7a12.png)

**Comment by sanderlv** [comment]
Ok ,heb mijn output in de ESP, maar hoe krijg ik deze in home assistant? Ik zie ze niet via MQTT gepublished worden....

![image](https://user-images.githubusercontent.com/16528916/97787214-22169a00-1bb1-11eb-800a-875b9b2548f1.png)

**Comment by sanderlv** [comment]
Ok, ontdekt (denk ik):
![image](https://user-images.githubusercontent.com/16528916/97800061-53837a00-1c32-11eb-9962-89c314f9cf7a.png)

MQTT explorer:
![image](https://user-images.githubusercontent.com/16528916/97800067-5aaa8800-1c32-11eb-828b-1fe2bb7bc8b0.png)

Rest nog 1 belangrijk punt... de waarden worden niet geupdate...

**Comment by arnemauer** [comment]
Beste Sander, vanwege een verhuizing heb ik geen tijd gehad om te reageren.
Ik probeer er deze week naar te kijken :)

>

**Comment by sanderlv** [comment]
Superbedankt alvast! Dit was de laatste hindernis in mijn homeassistant avontuur

**Comment by sanderlv** [comment]
> 
> Beste Sander, vanwege een verhuizing heb ik geen tijd gehad om te reageren. Ik probeer er deze week naar te kijken :)
> […](#)

Friendly reminder :-)

**Comment by arnemauer** [comment]
Wat bedoel je met de waarden worden niet geupdate? Bedoel je daarmee de waarden van de plugin (espeasy devices pagina) of bedoel je dat de waarden niet naar mqtt worden gestuurd?

Zou je een screenshot kunnen maken van de plugin configuratiepagina?

**Comment by sanderlv** [comment]
Ik bedoel de waarden van de duco via serial naar de esp. Mqtt werkt goed. Welke screenshot bedoel je? Die van hierboven?

**Comment by 26miller** [comment]
Ik zie dit fenomeen ook zo af en toe wat bij mij helpt is het device even op disable te zetten en vervolgens weer op enable.
Ben er nog niet achter wat dit veroorzaakt overigens.

**Comment by sanderlv** [comment]
Ik heb het maar 1 keer "gevuld" gehad. Ik heb nu net alles disbaled, minuut gewacht, enabled en dat doet niets...

![image](https://user-images.githubusercontent.com/16528916/98781747-2b94d300-23f7-11eb-966f-3b0515393816.png)

**Comment by arnemauer** [comment]
Je kan het beste stap voor stap plugins activeren.
- disable alle serial plugins
- enable alleen de ventilation_mode_main_plugin
- om meer informatie terug te zien in de logs kun je "Web Log Level" op DEBUG zetten (Tools -> Advanced Settings)
- kun je +- 2 minuten van de weblog hier posten? (Tools -> Log).

**Comment by sanderlv** [comment]
OMG 👎 Ik dacht even de DUCO uit e naa te zetten of dit werkt, en de fysieke situatie te beoordelen... en ik zie dat het draadje los ligt. Volledig doorgesneden door de deksel, die heeft de draad dus bij montage (vastklikken) volledig doorgesneden... Gemaakt en nu kome de waarden binnen... (shame).

Iedereen super bedankt voor de tijd en reacties! Nu begint het spelen...

**Comment by sanderlv** [comment]
Echt heel erg bedankt Arne! Dit is heel fijn om te weten/hebben/gebruiken!

nu kan ik de fan in de nacht bij een percentage vocht >65 UIT zetten ❤️ 

Het resultaat:
![image](https://user-images.githubusercontent.com/16528916/98788232-deb5fa00-2400-11eb-87db-035a5a09df7d.png)

![image](https://user-images.githubusercontent.com/16528916/98788518-49ffcc00-2401-11eb-8f77-be44f98e6d15.png)

**Comment by arnemauer** [comment]
Goed om te horen! Onderin de Ducobox zitten twee wartels waardoor je de kabel kan trekken. De voedingskabel zit door een van de wartels. De andere wartel is vrij :)

**Comment by sanderlv** [comment]
Die wartels zitten bij mij aan de zijkant. ook de printplaat ziet er anders uit dan jouw foto.

Ik heb een heel klein gaatje gemaakt en daar kabel doorheen...

**Comment by JohCo-hassio** [comment]
Hey Sanderlv, kunnen we kijken of wij met elkaar in contact kunnen komen, ik heb vandaag de gateway binnen gekregen.
Dit heb ik allemaal aan de gang gekregen gelukkig.
Alleen heb ik mega weinig verstand van MQTT naar home assistant enz (hier nog niet eerder iets mee gedaan) 
Home assistant ken ik wel goed :)
En ben ook heel benieuwd naar je node-red flow (beter goed gedeeld als slecht bedacht) hahaha

Gr Johan

**Comment by sanderlv** [comment]
Wat is je vraag?

**Comment by JohCo-hassio** [comment]
Hoe heb jij de gegevens in home assistant gekregen ik heb de MQTT via intergrations gekoppeld
En zou jij je node-red flow kunnen delen.

Misschien kunnen we even mailen rechtstreeks johan.doorstruur@gmail,com

**Comment by JohCo-hassio** [comment]
johan.doorstuur@gmail.com email verkeerd

**Comment by sanderlv** [comment]
Je zult een mqtt server moeren installeren. Ik weet niet hoe en welke installatie methode je hebt gekosen maar mocht je de mogelijkheid hebben via supervisor een addon te installeren moet je de mosquitto matt server installeren. Dáár laat je dan de esp van arne naartoe sturen. Wanneer je de mqtt integratie heb aangezet zouden alle topics automatisch moeten worden geïntegreerd. Er is heel veel informatie op community.home-assistant.io en op de manual pages van homeassistant te vinden.
