### ISSUE TITLE
Afwezigheidsstand

### ISSUE THREAD

**Issue by hilcoonline** [arnemauer/Ducobox-ESPEasy-Plugin#57]
Is het ook mogelijk om de afwezigheidsstand toe te voegen? Er staat niet duidelijk beschreven wat hij dan doet, maar het is de meest energiezuinige stand. Waarschijnlijk draait hij dan op zeer langzame snelheid.

**Comment by arnemauer** [comment]
De afwezigheidsstand zit al in de plugin verwerkt: https://github.com/arnemauer/Ducobox-ESPEasy-Plugin/blob/master/_P150_DucoRFGateway.ino#L304

Volgens mij is die stand gelijk aan de laagste stand.
