### ISSUE TITLE
Received change ventilation command

### ISSUE THREAD

**Issue by 26miller** [arnemauer/Ducobox-ESPEasy-Plugin#59]
Goedemorgen,

Mijn gateway valt met enige regelmaat stil. Het enige wat ik kan doen om het weer aan de gang te krijgen is de gateway van spanning te halen. In het log zie ik met enige regelmaat "Received change ventilation command" en dacht eigenlijk dat mijn script niet in orde was. (Ik heb een script lopen wat ventilatie naar aanstuurt afhankelijk van de humidity in badkamer), Ik heb het betreffende script inmiddels uit gezet maar blijf deze melding zien.  

Betekend deze melding dat gateway de box naar een andere stand wil zetten of is dit een systeem melding die ik verkeerd intrepteteer?
Kan dit een reden zijn van het "freezen" van mij gateway?

![image](https://user-images.githubusercontent.com/72555739/99240589-fe806000-27fc-11eb-96b9-5e859e89da38.png)

**Comment by arnemauer** [comment]
In de CC1101 chip zit een bug waardoor hij in ontvangermodus blijft staan maar niets ontvangt (zie errata Rev. E: https://www.ti.com/lit/pdf/swrz020) . Ik heb de code aangepast zodat dit niet meer voorkomt. 

Ik heb alle bugs gefixed en de gateway loopt nu weer stabiel :)
Ik hoor graag de nieuwe firmware bij jullie ook goed draait. 
e0e49de
