### ISSUE TITLE
[P150] DUCO RF GW: Initialisation -> calibration failed. No response from CC1101 or status not idle

### ISSUE THREAD

**Issue by lansi002** [arnemauer/Ducobox-ESPEasy-Plugin#60]
Hoi Arne en anderen,

Ik krijg een foutmelding bij het activeren van de RF gateway in ESPEasy.

[P150] DUCO RF GW: Initialisation -> calibration failed. No response from CC1101 or status not idle

Het lukt mij dan ook niet te  pairen met de DucoBox in installatiemode. Er verschijnt geen Join knop.
Het blijft alsvolgt:
![image](https://user-images.githubusercontent.com/63741975/99808792-ae2d3900-2b41-11eb-8450-82fbcd5d82cb.png)

Ik heb alle bedrading dubbel gecheckt en doorgemeten. 

Hier mijn nog opstelling voor wat het waard is in dit stadium van mijn vraag:
![image](https://user-images.githubusercontent.com/63741975/99808867-ca30da80-2b41-11eb-9c35-91afbb02d93b.png)

![image](https://user-images.githubusercontent.com/63741975/99808902-d7e66000-2b41-11eb-8014-30ca99f4f5a7.png)

Ik gebruik de volgende bin file op een nodemcu amico:
20200629 Flasher firmware 281cde1 29-06-2020 (ESPEasy mega-20200515)

De Serial Gateway werkt overigens al wel goed met de DucoBox.

Hopelijk kunnen je/jullie me beetje helpen om wat dingen te controleren.

UPDATE 2020-11-21: ook geprobeerd met een Wemos D1 mini, maar ook daar dezelfde melding. 

Groet,
André

**Comment by arnemauer** [comment]
Hoi André,

De melding "[P150] DUCO RF GW: Initialisation -> calibration failed. No response from CC1101 or status not idle" betekent dat de gateway niet kan communiceren met de CC1101 module. 

Als ik je foto bekijk valt mij op dat je de mosi (pin 3) op de CC1101 hebt aangesloten op 3V3. Heb je onderstaand schema gebruikt bij het aansluiten?

<img src="https://cdn.bitsandparts.nl/partpics/0001RFCC1101%5E6_zoom.jpg" />

**Comment by lansi002** [comment]
Hoi Arne,

Bedankt voor je reactie. Ik waardeer dat enorm.

Ik heb inderdaad dat schema gebruikt om de CC1101 aan te sluiten. Dit heb ik ook nog gecheckt met jou aansluitschema's (mappingstabel) en DucoGWv3 schematic.pdf.

Ik snap de verwarring, maar de 4 rechter draden (resp. zwart, rood, geel en oranje) gaan naar de seriële verbinding met de DucoBox.
He is de oranje op pin D7 die naar de CC1101 / MOSI gaat (en dus niet die op 3v3 zit op de Nodemcu).

Ik schrok al, dat ik er overeen had gekeken. Jammer dat wel, want had we het opgelost.

Hier mijn vertaalde kladje, maar is wel moeilijk leesbaar denk ik.
NB de paarse draad is niet in gebruik, maar voor het gemak op D2 aangesloten, anders bungelt die zo los.

![image](https://user-images.githubusercontent.com/63741975/99899740-f23c4d00-2cab-11eb-96bf-e4757421fc4a.png)

**Comment by lansi002** [comment]
Ik heb net een meting gedaan (mini oscilloscoop) op de signalen D1, D5, D6, D7, D8 bij het enablen van de RF plugin in ESPEasy. Zonder aangesloten CC101.
Dit omdat de plugin dan gelijk de CC1101 probeert te initialiseren.

Ik zie alleen wat bits voorbij komen op D5 en D8.
Op D6 en D7 zie ik niks gebeuren.

Oftewel de plugin lijkt wel iets te doen.

Ik vermoed dat de plugin vervolgens wacht op antwoord van de CC1101 alvorens weer wat te doen.

Vanavond de CC1101 erbij aansluiten en kijken of ik meer bits voorbij zie komen. Het is een beetje lastig meten vandaar dat ik dat niet gelijk mee heb genomen, maar ik wilde je dit alvast delen.

**Comment by arnemauer** [comment]
Op D7 (MOSI) zou je ook zeker activiteit moeten zien. Dit zijn de bytes die je zou moeten terug zien op D7: https://github.com/arnemauer/Ducobox-ESPEasy-Plugin/blob/3ddd3aa88b2ff08027076651f576b567183e834f/lib/Duco/DucoCC1101.cpp#L82

**Comment by lansi002** [comment]
Is dat data van MOSI naar D7 als reactie op activiteit op D5 / D8 ?

**Comment by arnemauer** [comment]
Nee, zie hieronder:

**D5 -> SCK**  = dit is het clock signaal dat er voor zorgt dat de master en de slave op dezelfde snelheid (de bitrate) met elkaar communiceren. Anders begrijpen ze elkaar niet.
**D6 -> MISO** = Master In Slave Out en is de verbdining waarmee de CC1101 communiceert met de ESP8266
**D7 -> MOSI** = Master Out Slave In en is de verbinding waarmee de ESP8266 met de CC1101 communiceert
**D8 -> CS =**   Chip Select (CS) hiermee wordt aangegeven met welke slave de master wil communiceren. Deze blijft laag zolang de ESP8266 communiceert met de CC1101.

**Comment by lansi002** [comment]
Ik heb nu alle pulsen gemeten met CC1101 aangesloten.

Bij het activeren van de RF plugin in ESPEasy zie ik dan het volgende:
D1 geen pulsen	(standaard hoog)
D5 wel pulsen 	(standaard laag)
D6 wel pulsen  	(standaard laag)
D7 geen pulsen 	(standaard laag)
D8 wel pulsen 	(standaard hoog) 

Ik vind het raar dat er niks over D7 gaat. Dat is toch de initialisatiedata die naar de CC1101 zou moeten gaan ?

Waar is D1 trouwens voor ? Is dat een interupt signaal van de CC1101, zodra er RF-remotesignaal ontvangen wordt door de CC1101 ?

Gr
André

**Comment by arnemauer** [comment]
Dat je signalen ziet op D6 is inderdaad een goede indicatie dat de CC1101 wel reageert. De clock op D5 zorgt ervoor dat de CC1101 een reactie geeft op D6.

**Comment by lansi002** [comment]
Tadaaaa:

![image](https://user-images.githubusercontent.com/63741975/100116060-97555200-2e73-11eb-9dbf-d9008dc6c342.png)

Ik heb Init SPI aangezet --> reboot ESPEasy --> klaar.

Dadelijk even met de DucoBox proberen.

**Comment by Sef1995** [comment]
@lansi002 Heb je misschien een linkje naar waar je die draadjes hebt gekocht die je aan de cc1101 heb gesoldeerd, aan de andere kant heb je het draadje vastgezet aan een female connector?
