### ISSUE TITLE
Not getting CO2 or RH values (CO2 Regelklep)

### ISSUE THREAD

**Issue by cpolhout** [arnemauer/Ducobox-ESPEasy-Plugin#61]
I configured P152 and P153 serial devices. I see in the serial log the response from my Focus, but the values are not set on the device. 

Please see the log:
![image](https://user-images.githubusercontent.com/20639809/100730512-6ffa0a00-33ca-11eb-8616-499d198550fd.png)

And the devices: (Also ventialtionmode is 0)
![image](https://user-images.githubusercontent.com/20639809/100731597-e1868800-33cb-11eb-87bf-88597b6ac55a.png)

**Comment by cpolhout** [comment]
Enabled serial-debug-logging.  Now it says invalid response:

![image](https://user-images.githubusercontent.com/20639809/100795883-0c9ac700-3420-11eb-974d-5ac812a6af31.png)

**Comment by lansi002** [comment]
Just to be sure:
Are the specific Ducobox CO2 and RH sensors connected ?

Like this:
https://www.duco.eu/nl/producten/mechanische-ventilatie/sturingscomponenten/boxsensor
or a Ducobox remote control with CO2 or RH sensors

**Comment by cpolhout** [comment]
Hi Ian,

Yes, they are added. I also connected with a usb2serial cable and used the Duco-software to configure the sensors. See screenshots beneath. I tried to use the serial-gateway option from the ESP, but that did not work also.

![image](https://user-images.githubusercontent.com/20639809/101284946-fce5fe80-37e2-11eb-944e-f23beb7f8121.png)
![image](https://user-images.githubusercontent.com/20639809/101284952-053e3980-37e3-11eb-8855-873cb0fd6583.png)

**Comment by lansi002** [comment]
Ik had het ook kunnen zien in je ESPeasy log, want er komen tenslotte 'Pakket ontvangen' voorbij.
Helaas heb ik zelf geen sensoren dus ik kan niet vergelijken wat er bij jou fout gaat.

**Comment by cpolhout** [comment]
@arnemauer Do you have an idea what might be wrong? I'm using the pre-build gateway from you.

**Comment by arnemauer** [comment]
De CO2 en RH sensors die je hebt zijn geen boxsensors. Vandaar dat je geen waardes krijgt.

Dit is het antwoord van je Ducobox: 20205b53454e534f525d20494E464F = "   [SENSOR] INFO"
Oftewel, geen boxsensoren.

**Comment by cpolhout** [comment]
Ah. Ok. Ik heb inderdaad kleppen met een sensor en geen losse sensoren. Ik wist niet dat daar verschil in zat. Zie bijgaand de logfile.

Vast bedankt voor het uitzoeken!
[DD_201230_Wednesday.log](https://github.com/arnemauer/Ducobox-ESPEasy-Plugin/files/5754731/DD_201230_Wednesday.log)

**Comment by Joost73** [comment]
@arnemauer , ik heb idd een boxsensor voor vocht.
Ik weet dat de boxsensor alleen het vochtpercentage meet en niet de temperatuur. Waarom staat de temperatuur dan wel bij de config? Daarnaast krijg ik ook geen waarde te zien. in de log staat: 

[P153] DUCO BOX SENSOR: start read, eventid:153384887: 
[P153] DUCO BOX SENSOR: Serial port in use, set flag to read data later.

Enig idee hoe ik dit kan oplossen?

![config](https://user-images.githubusercontent.com/38922912/115231144-8274a600-a115-11eb-9b9d-e0e8fce9b110.PNG)

**Comment by arnemauer** [comment]
> Ah. Ok. Ik heb inderdaad kleppen met een sensor en geen losse sensoren. Ik wist niet dat daar verschil in zat. Zie bijgaand de logfile.
> 
> Vast bedankt voor het uitzoeken!
> [DD_201230_Wednesday.log](https://github.com/arnemauer/Ducobox-ESPEasy-Plugin/files/5754731/DD_201230_Wednesday.log)

Ik kan in de log helaas niet het commando vinden voor het opvragen van de luchtvochtigheid van de klep. Zou je de stappen nog een keer willen proberen? Om er zeker van te zijn dat alle informatie in de log staat zou je een aantal keer op refresh all kunnen klikken.

**Comment by arnemauer** [comment]
Waarschijnlijk lost de nieuwste firmware je probleem op: https://github.com/arnemauer/Ducobox-ESPEasy-Plugin/commit/4e4d3791da5bb5204a622e2e6e2d3380ea2f31c2
