### ISSUE TITLE
Joinen met duco box werkt niet

### ISSUE THREAD

**Issue by Carlozzz92** [arnemauer/Ducobox-ESPEasy-Plugin#63]
Ik heb een Wemos D1 mini met een CC1101 module die ik wil koppelen aan mijn Ducobox.
De firmware die ik gebruik is: 20200629 Firmware 281cde1 29-06-2020 (ESPEasy mega-20200515)

Na het activeren van de installermode via de duco box heb ik op de join knop gedrukt. (Groene ledje knippert)
In de log verschijnen de volgende regels, maar de wemos met CC1101 maakt geen verbinding met de duco box.
Klopt het dat de GDO0 pin van de CC1101 niet met de wemos verbonden hoeft te worden?

![afbeelding](https://user-images.githubusercontent.com/64526157/102608223-d94b7e00-4129-11eb-8492-c634dcf73758.png)
![afbeelding](https://user-images.githubusercontent.com/64526157/102608703-98a03480-412a-11eb-9e51-e98fc0de0e00.png)

**Comment by Carlozzz92** [comment]
Does anyone know a solution? how to connect to the duco box?

**Comment by arnemauer** [comment]
Voor zover ik kan zien wordt er wel een join bericht verstuurd. Daarna volgt er geen reactie van de Ducobox.
Er is wel vrij snel radio activiteit (ongeveer 60ms na het versturen van het join pakket) maar dat het pakket wordt genegeerd omdat het niet goed is ontvangen (Ignoring RF noise). 

Wat is de afstand tussen de gateway en de Ducobox?

**Comment by Carlozzz92** [comment]
Ik heb het vanmorgen op verschillende afstanden geprobeerd (1 meter vanaf de duco box en een verdieping onder de ducobox) maar beide keren weer met hetzelfde resultaat, dat het signaal niet goed wordt ontvangen(Ignoring RF noise).

**Comment by arnemauer** [comment]
> Klopt het dat de GDO0 pin van de CC1101 niet met de wemos verbonden hoeft te worden?
GO0 hoeft inderdaad niet aangesloten te worden.

Als je de RF-bedieningsschakelaar gebruikt zie je dan wel berichten langskomen?
Heb je een CC1101 module voor 868mhz of 433mhz?

**Comment by Carlozzz92** [comment]
Ik heb een CC1101 module voor 868mhz. ik zie niks voorbijkomen als ik de RF-schakelaar gebruik.

**Comment by arnemauer** [comment]
Zou je een foto willen posten van hoe je alles hebt aangesloten?

**Comment by Carlozzz92** [comment]
![20201231_185359](https://user-images.githubusercontent.com/64526157/103431798-50771c80-4bd6-11eb-852c-8e8d4593003b.jpg)
![20201231_185416](https://user-images.githubusercontent.com/64526157/103431802-6389ec80-4bd6-11eb-8b10-f0adb51b4979.jpg)

**Comment by Predjee** [comment]
Ik kan exact hetzelfde doen qua foto's met exact dezelfde aansluiting en hetzelfde "issue". Ik heb geen idee meer waar het nog fout gaat. Ik heb zelfs al bovenop de ducobox gezeten.

**Comment by MichelFalke** [comment]
Ik heb het vandaag kunnen oplossen! Het issue was dat ik nog net twee kleine stukjes microscopisch groot tin tegen elkaar aan had zitten.

**Comment by benvandijk84** [comment]
Hier hetzelfde probleem zie [closed issue.](https://github.com/arnemauer/Ducobox-ESPEasy-Plugin/issues/48)
Heb een nieuwe besteld, aangesloten maar geeft hetzelfde resultaat helaas.

**Comment by arnemauer** [comment]
Kun je een scherpe foto van je WEMOS d1 maken (van beide kanten)?

Wat staat er op dit onderdeel?
![103431798-50771c80-4bd6-11eb-852c-8e8d4593003b](https://user-images.githubusercontent.com/268051/104853861-e4015a80-5903-11eb-8da0-d3ab6d84cce0.jpg)

**Comment by Carlozzz92** [comment]
Op het onderdeel in het rode vierkantje staat 4A2D (zie foto hieronder)

![4A2D](https://user-images.githubusercontent.com/64526157/104902350-f076c900-597e-11eb-99a8-ecd5658242d0.jpeg)

De weblog laat bij het drukken op Submit/Save op de Config pagina het onderstaande resultaat zien:

![afbeelding](https://user-images.githubusercontent.com/64526157/104902732-5ebb8b80-597f-11eb-81e7-74335d58d29c.png)

**Comment by z6SVGEL9Q6a1** [comment]
Ik heb een gelijksoortig probleem;
- NodeMCU v3 
- TI-C1101 868mhz (andere chip dan op bovenstaande foto)
- AFM 281cde1: Jun 29 2020

------------ log bij joinen
1008597: [P150] DUCO RF GW: TIMER => 1008596 1008594 2
1008597: [P150] DUCO RF GW: Start of RF signal received
1008598: [P150] DUCO RF GW: Ignoring RF noise
1008877: [P150] DUCO RF GW: TIMER => 1008876 1008864 12
1008877: [P150] DUCO RF GW: Start of RF signal received
1008877: [P150] DUCO RF GW: Ignoring RF noise

------------ log bij saven
234666: Webserver args: 0: 'index' length: 1 1: 'page' length: 1
240611: SaveToFile: free stack: 3328
240674: FILE : Saved config.dat
240674: SaveToFile: free stack after: 3328
240675: SaveToFile: free stack: 2992
240687: FILE : Saved security.dat
240687: SaveToFile: free stack after: 2992
240701: [P150] DUCO RF GW: Extra Settings PLUGIN_150 loaded
240711: [P150] DUCO RF GW: Values set from config. DeviceID: 0, networkId: 0000, radio power: Default - radio power 0,6 dBm (0x8D)
240714: [P150] DUCO RF GW: CC1101 868Mhz transmitter initialized

**Comment by arnemauer** [comment]
> Op het onderdeel in het rode vierkantje staat 4A2D (zie foto hieronder)
> 
> ![4A2D](https://user-images.githubusercontent.com/64526157/104902350-f076c900-597e-11eb-99a8-ecd5658242d0.jpeg)

Waarschijnlijk heb je een clone via Aliexpress gekocht. Om het product zo goedkoop mogelijk te maken gaat zo'n chinees kijken waar hij de kosten kan drukken. De voltage regulator is daar een van.  De 4A2D voltage regulator levert maximaal 150mA. De ESP8266 gebruikt in piekmomenten 430mA. De CC1101 gebruikt tijdens het zenden 30mA.  Er is dus veel te weinig stroom om alles stabiel te voeden. Ik heb zelf deze modules ook gebruikt en het vervelende is dat het lijkt alsof ze prima werken maar na verloop van tijd ga je vreemde problemen ervaren (uitval, corrupte memory, reboots, etc.).

Zouden jullie de CC1101 kunnen voeden met een externe 3.3v voeding? En dan kijken of je de signalen van een afstandsbediening wel goed kunnen ontvangen?

**Comment by lansi002** [comment]
Hallo Carloz,

Ik gebruik deze van aliexpress en werkt prima:
https://nl.aliexpress.com/item/4000264911320.html?spm=a2g0s.9042311.0.0.27424c4dq618Lh

**Comment by Carlozzz92** [comment]
Ik heb een nieuwe Wemos D1 mini en een nieuwe CC1101 gekocht en nu werkt het inderdaad wel. De signalen van de draadloze bediening worden opgepakt en ik kan de Duco box nu ook bedienen vanuit de interface van de Wemos D1 mini.
Blijkbaar zat het probleem inderdaad in de hardware.

**Comment by Sef1995** [comment]
@Carlozzz92 Zou je misschien een linkje kunnen sturen van de draden die je gebruikt hebt die je aan de CC1101 hebt gesoldeerd. Aan de andere kant van die draden heb je er ook connectors op zitten zie ik.. ik kan ze zelf nergens vinden.. ☺️
