### ISSUE TITLE
Vragen

### ISSUE THREAD

**Issue by johannienhuis** [arnemauer/Ducobox-ESPEasy-Plugin#64]
Beste Arne,
Ik overweeg om een gateway te bestellen via je bestelformulier. Even een paar vragen om te checken of ik alles goed heb begrepen.

1. is het apparaat dat ik kan bestellen een serial-gateway en een rf-gateway in 1 device?
2. voor HA heb je deze pagina opgenomen: https://github.com/arnemauer/Ducobox-ESPEasy-Plugin/wiki/Home-Assistant. Moet ik iets extra's doen om een mosquitto server te draaien of is het zo simpel om alleen de commando's uit te laten voeren door HA?
3. staat de niewste firmware op het apparaat of moet ik zelf firmware uploaden?

Hoor graag van je.

Gr.
Johan

**Comment by arnemauer** [comment]
Hoi Johan,

1. Klopt helemaal.
2. Die pagina moet inderdaad nog opgevuld worden. Ik heb zelf geen ervaring met HASS. Al wil ik binnenkort wel overstappen van Domoticz naar HASS. De gateway kan via o.a. mqtt de data verzenden naar HASS. Ik denk dat je dan een mosquito server moet instellen om die berichten te ontvangen.
3. De nieuwe firmware staat op de gateway.

Groet,

Arne
