### ISSUE TITLE
mDNS ondersteuning

### ISSUE THREAD

**Issue by lansi002** [arnemauer/Ducobox-ESPEasy-Plugin#67]
Hallo

Ik gebruik de volgende firmware:
20200629 Flasher firmware 281cde1 29-06-2020 (ESPEasy mega-20200515)

Ondersteunt deze firmware ook mDNS ? Ik kan het niet vinden in de code.
Ik wil graag de NodeMCU bereiken middels hostname.

Ik kreeg deze reactie nog van TD-er ESPEasy zelf (Owner and lead developer of ESPeasy):
_Have you tried a build with mDNS enabled?
test_ESP8266_4M1M_VCC_MDNS_SD is too big lately so that PIO env. is not included in the latest builds.
But in the "custom" builds, the FEATURE_MDNS flag is set so it should be included._

**Comment by arnemauer** [comment]
Hej,

Ik kan vanavond kijken of ik een binary kan maken voor je. Ik weet niet of ik dit in de standaard binaries mee kan nemen. Dat  hangt er vanaf hoeveel extra ruimte het inneemt :)

**Comment by lansi002** [comment]
Hoi,

Een oplossing voor mij zou ook zijn dat ik met mqtt de stand kan bepalen van de Ducobox vanuit een Domoticz schakelaar.
Dus ipv de volgende requesten per stande een mqtt request:
![image](https://user-images.githubusercontent.com/63741975/105579404-ae86c200-5d86-11eb-97a5-3d8404f33ed5.png)

**Comment by lansi002** [comment]
Ik heb het als volgt opgelost:

![image](https://user-images.githubusercontent.com/63741975/112496712-4011b080-8d85-11eb-9c79-20c880654120.png)

SentMQTTFromDomoticz.sh:

#!/bin/sh
# aanroep vanuit Domoticz switch: script://SentMQTTFromDomoticz.sh ESPEasy_DucoBox/Ventilationmode 3
# param 1: topic
# param 2: message/payload
#echo $(date)" Start sending MQTT message" >> /home/pi/SentMQTTFromDomoticz.log
mosquitto_pub -t $1 -m $2
#echo $(date)" Done " $1 >> /home/pi/SentMQTTFromDomoticz.log

**Comment by lansi002** [comment]
Nog een tip:

Vanaf een andere ESPEasy met humidity sensor in de badkamer kun je bijvoorbeeld de Duco automatisch op de hoogste stand zetten, zonder zelf op de remote van de Duco te drukken (dus geen batterij wissel meer nodig van deze remotes).

ESPEasy device:
![image](https://user-images.githubusercontent.com/63741975/112498357-be228700-8d86-11eb-9c97-5b509244fcff.png)

![image](https://user-images.githubusercontent.com/63741975/112498394-c7abef00-8d86-11eb-99d4-454bd17d8774.png)


ESPEasy rules:
![image](https://user-images.githubusercontent.com/63741975/112498443-d2668400-8d86-11eb-8033-e7cea91b0191.png)

ESPEasy zelf op een Wemos D1 mini:
![image](https://user-images.githubusercontent.com/63741975/112498718-15285c00-8d87-11eb-84ae-d19a3ef60927.png)
