### ISSUE TITLE
Home Assistant Instructies maken

### ISSUE THREAD

**Issue by ericmulder** [arnemauer/Ducobox-ESPEasy-Plugin#73]
Ik heb de ducobox-ESPEasy aan de praat gekregen met mqtt en home assistant. Graag zou ik een tutorial wilen schrijven voor de wiki. Maar als ik de repo fork gaat de wiki niet mee. Heeft deze andere schrijf en lees rechten?

**Comment by arnemauer** [comment]
Hoi Eric, Super dat je wilt helpen om de wiki te vullen! Ik heb vandaag een begin gemaakt en hoor graag je aanvullingen/verbeteringen! #24
