### ISSUE TITLE
Zijn er nog Gateway's beschikbaar

### ISSUE THREAD

**Issue by klaaspiet** [arnemauer/Ducobox-ESPEasy-Plugin#76]
Zijn er nog gateways beschikbaar.
zijn met een nieuwbouwhuis bezig en zoals het nu lijkt komt daar een Duco systeem in dus zou graag willen weten of ze nog beschikbaar zijn.  Dan zou ik wel interesse hebben.

**Comment by arnemauer** [comment]
Hoi KlaasPiet, zie de link op de readme pagina :) https://github.com/arnemauer/Ducobox-ESPEasy-Plugin

**Comment by klaaspiet** [comment]
Huis is klaar en is een Duco geworden aanvraag is verstuurd voor een complete gateway. 
Nu nog ff wachten tot februari lees ik.
Eerst maar eens de lampen, zonneschermen en verbruikers in kaart brengen.

**Comment by arnemauer** [comment]
Ik verwacht met 1-2 weken weer een aantal op voorraad te hebben. Je ontvangt tzt een email ;)

**Comment by klaaspiet** [comment]
Heb je al weer onderdelen gekregen. Ben erg nieuwsgierig 😀
