### ISSUE TITLE
Ducobox 325 RF supported?

### ISSUE THREAD

**Issue by jonskoglund** [arnemauer/Ducobox-ESPEasy-Plugin#78]
Does the Ducobox 325 RF work with your plugin? I stumbled upon this and I'm very excited to integrate it with homeassistant.
I don't know what kind of ports I should look for on my unit. What PCB should my Ducobox have to be compatible?

**Comment by arnemauer** [comment]
Voor zover ik weet heeft de Ducobox 325 RF geen connector voor een seriële verbinding. De RF gateway zou wel moeten werken.
Voor de seriele verbinding is deze connector nodig:

![](https://github.com/arnemauer/Ducobox-ESPEasy-Plugin/raw/master/Screenshots/DUCOBOX-CONNECTOR.jpg)

**Comment by MartijnDisse** [comment]
I have an Ducobox Energy Premium 325 and that one has the required serial port. But I get strange serial values.

**Comment by arnemauer** [comment]
> I have an Ducobox Energy Premium 325 and that one has the required serial port. But I get strange serial values.

De Ducobox 325 RF is een oud type ducobox (+-10 jaar oud) ;) Heel anders dan de Ducobox Energy Premium 325 (die heeft veel meer functies).
