### ISSUE TITLE
Incorrect values send for Domoticz

### ISSUE THREAD

**Issue by Pinkel** [arnemauer/Ducobox-ESPEasy-Plugin#8]
When using the 4 separate IDX values, all updates will have the same ("flow percentage") value, instead of separate values.

**Comment by arnemauer** [comment]
Fixed by dividing functionality over multiple plugins :) Please check the device table on the wiki: https://github.com/arnemauer/Ducobox-ESPEasy-Plugin/wiki/Configureren---Serial-gateway#configureren-van-de-plugins
