### ISSUE TITLE
Ducobox rf 325 ondersteuning?

### ISSUE THREAD

**Issue by hetiswatofniet** [arnemauer/Ducobox-ESPEasy-Plugin#83]
Hi!
Ik wil mijn RF 325 uit 2012 koppelen met behulp van deze plugin, hij lijkt alleen het join commando niet op te vangen. 
Is er een manier om dit werkend te krijgen?

**Comment by arnemauer** [comment]
Zie #78

Voor zover ik weet heeft de Ducobox 325 RF geen connector voor een seriële verbinding. De RF gateway zou wel moeten werken.
