### ISSUE TITLE
Joinen werkt niet

### ISSUE THREAD

**Issue by xylone** [arnemauer/Ducobox-ESPEasy-Plugin#89]
Zojuist de gateway ontvangen en direct mee aan de slag. 
Tutorial gevolgd (Hulde voor de uitgebreide en duidelijke uitleg!)
Na het klikken van de Join gewacht, maar netwerk ID wordt niet gevonden:
15348: [P150] DUCO RF GW: UPDATE by PLUGIN_READ
15349: [P150] DUCO RF GW:  State: 0.00
20348: [P150] DUCO RF GW: UPDATE by PLUGIN_READ
20349: [P150] DUCO RF GW:  State: 0.00
25348: [P150] DUCO RF GW: UPDATE by PLUGIN_READ
25349: [P150] DUCO RF GW:  State: 0.00
26146: [P150] DUCO RF GW: 26146 - RECEIVED message: SRC:1; DEST:4; ORG.SRC:1; ORG.DEST:4; Ntwrk:00094404;Type:6; Bytes:9; Counter:15; 
26147: [P150] DUCO RF GW: 26146 - 
26147: [P150] DUCO RF GW: 26146 - Ignore message, not our networkID.
28326: [P150] DUCO RF GW: 28326 - RECEIVED message: SRC:1; DEST:4; ORG.SRC:1; ORG.DEST:4; Ntwrk:00094404;Type:7; Bytes:13; Counter:11;
28327: [P150] DUCO RF GW: 28326 - 20,00,12,00,
28327: [P150] DUCO RF GW: 28326 - Ignore message, not our networkID.
30348: [P150] DUCO RF GW: UPDATE by PLUGIN_READ
30349: [P150] DUCO RF GW:  State: 0.00
31721: WD   : Uptime 1 ConnectFailures 0 FreeMem 5744 WiFiStatus 3 ESPeasy internal wifi status: Conn. IP Init
35348: [P150] DUCO RF GW: UPDATE by PLUGIN_READ
35349: [P150] DUCO RF GW:  State: 0.00
40348: [P150] DUCO RF GW: UPDATE by PLUGIN_READ
40349: [P150] DUCO RF GW:  State: 0.00
45348: [P150] DUCO RF GW: UPDATE by PLUGIN_READ
45349: [P150] DUCO RF GW:  State: 0.00
50348: [P150] DUCO RF GW: UPDATE by PLUGIN_READ
50349: [P150] DUCO RF GW:  State: 0.00
55348: [P150] DUCO RF GW: UPDATE by PLUGIN_READ
55349: [P150] DUCO RF GW:  State: 0.00
56173: [P150] DUCO RF GW: 56172 - RECEIVED message: SRC:1; DEST:4; ORG.SRC:1; ORG.DEST:4; Ntwrk:00094404;Type:6; Bytes:9; Counter:1; R
56173: [P150] DUCO RF GW: 56172 - 
56173: [P150] DUCO RF GW: 56173 - Ignore message, not our networkID.
58348: [P150] DUCO RF GW: 58348 - RECEIVED message: SRC:1; DEST:4; ORG.SRC:1; ORG.DEST:4; Ntwrk:00094404;Type:7; Bytes:13; Counter:12;
58349: [P150] DUCO RF GW: 58348 - 20,00,12,00,
58349: [P150] DUCO RF GW: 58348 - Ignore message, not our networkID.
60348: [P150] DUCO RF GW: UPDATE by PLUGIN_READ
60349: [P150] DUCO RF GW:  State: 0.00
60388: [P150] DUCO RF GW: 60387 - RECEIVED message: SRC:1; DEST:0; ORG.SRC:1; ORG.DEST:0; Ntwrk:00094417;Type:7; Bytes:13; Counter:5; 
60388: [P150] DUCO RF GW: 60388 - 20,00,52,00,
60389: [P150] DUCO RF GW: 60388 - Ignore message, not our networkID.
61721: WD   : Uptime 1 ConnectFailures 0 FreeMem 5520 WiFiStatus 3 ESPeasy internal wifi status: Conn. IP Init
65349: [P150] DUCO RF GW: UPDATE by PLUGIN_READ
65349: [P150] DUCO RF GW:  State: 0.00
70348: [P150] DUCO RF GW: UPDATE by PLUGIN_READ
70349: [P150] DUCO RF GW:  State: 0.00
75349: [P150] DUCO RF GW: UPDATE by PLUGIN_READ
75349: [P150] DUCO RF GW:  State: 0.00
80348: [P150] DUCO RF GW: UPDATE by PLUGIN_READ
80349: [P150] DUCO RF GW:  State: 0.00
85348: [P150] DUCO RF GW: UPDATE by PLUGIN_READ
85349: [P150] DUCO RF GW:  State: 0.00
86207: [P150] DUCO RF GW: 86206 - RECEIVED message: SRC:1; DEST:4; ORG.SRC:1; ORG.DEST:4; Ntwrk:00094404;Type:6; Bytes:9; Counter:2; R
86207: [P150] DUCO RF GW: 86207 - 
86208: [P150] DUCO RF GW: 86207 - Ignore message, not our networkID.
88166: [P150] DUCO RF GW: 88165 - RECEIVED message: SRC:1; DEST:0; ORG.SRC:1; ORG.DEST:0; Ntwrk:00091a4a;Type:0; Bytes:10; Counter:6; 
88166: [P150] DUCO RF GW: 88165 - 00,
88166: [P150] DUCO RF GW: 88166 - Ignore message, not our networkID.
88386: [P150] DUCO RF GW: 88385 - RECEIVED message: SRC:1; DEST:4; ORG.SRC:1; ORG.DEST:4; Ntwrk:00094404;Type:7; Bytes:13; Counter:13;
88386: [P150] DUCO RF GW: 88386 - 20,00,12,00,
88387: [P150] DUCO RF GW: 88386 - Ignore message, not our networkID.
90348: [P150] DUCO RF GW: UPDATE by PLUGIN_READ
90349: [P150] DUCO RF GW:  State: 0.00
91722: WD   : Uptime 2 ConnectFailures 0 FreeMem 5272 WiFiStatus 3 ESPeasy internal wifi status: Conn. IP Init
95348: [P150] DUCO RF GW: UPDATE by PLUGIN_READ
95349: [P150] DUCO RF GW:  State: 0.00
100348: [P150] DUCO RF GW: UPDATE by PLUGIN_READ
100349: [P150] DUCO RF GW:  State: 0.00
105348: [P150] DUCO RF GW: UPDATE by PLUGIN_READ
105349: [P150] DUCO RF GW:  State: 0.00
110348: [P150] DUCO RF GW: UPDATE by PLUGIN_READ
110349: [P150] DUCO RF GW:  State: 0.00
112156: [P150] DUCO RF GW: 112156 - RECEIVED message: SRC:1; DEST:0; ORG.SRC:1; ORG.DEST:0; Ntwrk:0008bacd;Type:7; Bytes:13; Counter:4;
112157: [P150] DUCO RF GW: 112156 - 20,00,52,00,
112157: [P150] DUCO RF GW: 112156 - Ignore message, not our networkID.
115348: [P150] DUCO RF GW: UPDATE by PLUGIN_READ
115349: [P150] DUCO RF GW:  State: 0.00
120348: [P150] DUCO RF GW: UPDATE by PLUGIN_READ
120349: [P150] DUCO RF GW:  State: 0.00
121721: WD   : Uptime 2 ConnectFailures 0 FreeMem 5104 WiFiStatus 3 ESPeasy internal wifi status: Conn. IP Init
125349: [P150] DUCO RF GW: UPDATE by PLUGIN_READ
125349: [P150] DUCO RF GW:  State: 0.00
130348: [P150] DUCO RF GW: UPDATE by PLUGIN_READ
130349: [P150] DUCO RF GW:  State: 0.00

**Comment by arnemauer** [comment]
In de log zie ik niet terug dat je het join commando hebt gegeven. Wil je de weblog open houden en vervolgens het join commando in een ander venster aanklikken?
