### ISSUE TITLE
RF gateway verwijderen in Duco box

### ISSUE THREAD

**Issue by Jimboer** [arnemauer/Ducobox-ESPEasy-Plugin#98]
Is het ook mogelijk het RF gateway component te verwijderen?  Ik heb hem nu twee keer gejoined staan (node 5 en 6).
Ook het network id weet ik niet meer, is deze te achterhalen via de Network Tool?

![2022-04-09 17_51_57-Duco Network Tool (USB)](https://user-images.githubusercontent.com/24806213/162999499-9da77531-77ef-42d7-9f10-6c47fb776b09.jpg)

**Comment by Jimboer** [comment]
Het is gelukt on RF gateway weer aan ter zetten na firmwareversie van gisteren! Lijkt nu stabiel op eerste gezicht.
Maar ik kan installer mode wel activeren, maar geen unjoin command geven. Hij geeft ook aan NOT ACTIVE terwijl hij wel actief is (led knippert).

**Comment by Jimboer** [comment]
@arnemauer is er een handmatig commando voor Unjoin?

**Comment by arnemauer** [comment]
DISJOIN 😃

**Comment by Jimboer** [comment]
INSTALLERMODE, DISJOIN of
VENTMODE, DISJOIN ?

**Comment by arnemauer** [comment]
Gewoon:
DISJOIN

**Moet voor een firmware update ook RJ45 kabel worden losgekoppeld en DUCO box uitgezet om RJ45 weer aan te kunnen sluiten?** 
De RJ11 kabel inderdaad even loskoppelen voor de upgrade. Bij voorkeur de upgrade uitvoeren via de usb-kabel om eerst de blank.bin te flashen en vervolgens de firmware.
